modLoader="javafml"
loaderVersion="[43,)"
license="MPL-2.0"
issueTrackerURL="https://github.com/Tslat/TslatEntityStatus/issues"

[[mods]]
modId="tslatentitystatus"
version="1.0.1"
displayName="TES"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
View entity health and other statuses. Make smacking things fun again!
'''

[[dependencies.tslatentitystatus]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.tslatentitystatus]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"
