[versions]
# TES
    tes = "1.9.2"

# Common
    minecraft-range = "[1.21.11,)"
    minecraft = "1.21.11"
    parchment-minecraft = "1.21.10"
    parchment = "2025.10.12"
    neoform = "1.21.11-20251209.172050"
    jopt-simple = "5.0.4"
    java = "21"

# Fabric
    fabric = "0.18.2"
    fabric-range = "0.18"
    fabric-api = "0.139.4+1.21.11"
    fabric-api-range = "0.139.0+1.21.11"

# Forge
    forge-fml-range = "[61,)"
    forge-range = "[61.0.2,)"
    forge = "61.0.2"
    forge-mc = "1.21.11-61.0.2"
    forge-eventbusvalidator = "7.0-beta.10"

# Neoforge
    neoforge-loader-range = "[5,)"
    neoforge-range = "[21.11.0-beta,)"
    neoforge = "21.11.0-beta"

# Dependencies
    mixin = "0.8.7"
    mixinextras = "0.5.0"
    mixinextras-range = "[0.5.0,)"
    forgeconfigapiport = "21.11.1"
    forgeconfigapiport-range = "[21.11.0,)"
    forgeconfigapiport-forge = "21.11.1"

# Plugins
    plugin-moddevgradle = "2.0.123"
    plugin-minotaur = "2.8.10"
    plugin-curseforge-gradle = "1.1.28"
    plugin-idea-ext = "1.3"
    plugin-forge-gradle = "[7.0.0-alpha.46,)"
    plugin-forge-at = "[5.0.1,)"
    plugin-forge-eventbusvalidator = "7.0-beta.10"
    plugin-loom = "1.14-SNAPSHOT"

[libraries]
# Mixin
    mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
    mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }
    mixinextras-forge = { group = "io.github.llamalad7", name = "mixinextras-forge", version.ref = "mixinextras" }

# Platform
    neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
    forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-mc" }
    fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
    fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
    minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Other
    forgeconfigapiport-common = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapiport" }
    forgeconfigapiport-fabric = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
    forgeconfigapiport-forge = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-forge", version.ref = "forgeconfigapiport-forge" }

[plugins]
# Publishing
    minotaur = { id = "com.modrinth.minotaur", version.ref = "plugin-minotaur" }
    curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "plugin-curseforge-gradle" }

# Platform
    moddevgradle = { id = "net.neoforged.moddev", version.ref = "plugin-moddevgradle" }
    forgegradle = { id = "net.minecraftforge.gradle", version.ref = "plugin-forge-gradle" }
    forge-at = { id = "net.minecraftforge.accesstransformers", version.ref = "plugin-forge-at" }
    forge-eventbusvalidator = { id = "net.minecraftforge.eventbus-validator", version.ref = "plugin-forge-eventbusvalidator" }
    loom = { id = "fabric-loom", version.ref = "plugin-loom" }

# Misc
    ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin-idea-ext" }